#!/usr/bin/env bash
set -euo pipefail

# CBDGold Manual Blueprint Creation Guide
# Since Render CLI isn't available, use this as a manual checklist

echo "🚀 CBDGold Blueprint Deploy - Manual Steps"
echo "=========================================="
echo ""

echo "Current commit to deploy: $(git rev-parse HEAD)"
echo "Repository: queenofwands888/CBDGold"
echo "Branch: main"
echo ""

echo "📋 Step-by-step blueprint deployment:"
echo ""
echo "1. Open Render Dashboard (https://dashboard.render.com)"
echo "   → Click 'New +' → 'Blueprint Deploy'"
echo ""
echo "2. Connect Repository:"
echo "   → Select 'queenofwands888/CBDGold'"
echo "   → Branch: 'main'"
echo "   → Blueprint file: render.yaml (at root)"
echo ""
echo "3. Review Services (from render.yaml):"
echo "   ✓ cbdgold-backend (Node.js web service)"
echo "     - Root: projects/CBDGold/backend"
echo "     - Build: npm install"
echo "     - Start: npm run start"
echo ""
echo "   ✓ cbdgold-frontend (Static site)"
echo "     - Root: projects/CBDGold"
echo "     - Build: npm install && npm run build"
echo "     - Publish: dist"
echo ""
echo "4. Environment Variables (set after deploy):"
echo "   Backend:"
echo "   - NODE_ENV=production"
echo "   - FRONTEND_URL=<frontend-url-from-render>"
echo "   - EMAIL_* vars (if needed)"
echo "   - ALGOD_* vars (if needed)"
echo ""
echo "   Frontend:"
echo "   - VITE_API_URL=<backend-url-from-render>"
echo "   - SKIP_CLIENT_GEN=1"
echo "   - VITE_ALGOD_* vars (for on-chain)"
echo ""
echo "5. Deploy & Test:"
echo "   → Click 'Apply' to create services"
echo "   → Monitor build logs (should show npm commands, not Docker)"
echo "   → Test both URLs once green"
echo ""
echo "6. Clean up:"
echo "   → Disable/delete old Docker services to avoid confusion"
echo "   → Update custom domains if needed"
echo ""
echo "🔍 If build fails, check logs for:"
echo "   ❌ 'Dockerfile' errors = still using old Docker service"
echo "   ✅ 'npm install' logs = using correct blueprint"
echo ""
echo "🎯 Expected build output:"
echo "   Backend: npm install → npm run start"
echo "   Frontend: npm install → npm run build → dist/"