[algokit]
min_version = "v2.0.0"

[project]
type = "contract"
name = "CBDGoldGovernance"
app_spec_path = "governance.arc32.json"
artifacts = "."

[project.run]
build = { commands = ["python governance_contract.py"], description = "Compile governance TEAL artifacts" }
