[algokit]
min_version = "v2.0.0"

[project]
type = "contract"
name = "CBDGoldStaking"
app_spec_path = "staking.arc32.json"
artifacts = "."

[project.run]
build = { commands = ["python staking_contract.py"], description = "Compile staking TEAL artifacts" }
