[algokit]
min_version = "v2.0.0"

[project]
type = "contract"
name = "CBDGoldPrize"
app_spec_path = "prize.arc32.json"
artifacts = "."

[project.run]
build = { commands = ["python prize_contract.py"], description = "Compile prize TEAL artifacts" }
