[algokit]
min_version = "v2.0.0"

[project]
type = "frontend"
name = 'CBDGold'
artifacts = "src/contracts"

[project.run]
build = { commands = ['npm run build'], description = 'Build frontend' }
test = { commands = ['npm run test'], description = 'Run frontend tests' }

[generate.client]
output_path = "src/contracts/clients"

[[project.contracts]]
type = "python"
name = "CBDGoldStaking"
path = "../CBDGoldStaking"

[[project.contracts]]
type = "python"
name = "CBDGoldPrize"
path = "../CBDGoldPrize"

[[project.contracts]]
type = "python"
name = "CBDGoldGovernance"
path = "../CBDGoldGovernance"
